"use client";

import { useEffect, useMemo, useState } from "react";
import { BarChart3, CheckCircle2, ClipboardList, DollarSign, FileText, PackageCheck, RefreshCw, Search, Ship, ShoppingCart, Star, Store, Users } from "lucide-react";
import { supabase } from "@/lib/supabase";

type Tab = "dashboard" | "solicitudes" | "rfq" | "cotizaciones" | "ordenes" | "importaciones" | "proveedores";

type Dashboard = { total_requests:number; pending_requests:number; approved_requests:number; active_rfqs:number; supplier_quotes:number; open_pos:number; po_total:number; active_suppliers:number; active_imports:number; };
type RequestRow = { id:string; request_code:string; requested_by_name:string|null; department:string|null; priority:string; request_type:string; title:string; description:string|null; needed_by:string|null; estimated_total:number; status:string; items_count:number; items_total:number; };
type RFQ = { id:string; rfq_code:string; request_code:string|null; title:string; description:string|null; status:string; due_date:string|null; currency:string; items_count:number; quotes_count:number; best_quote_total:number|null; };
type Quote = { id:string; rfq_code:string; rfq_title:string; supplier_code:string; supplier_name:string; country:string; supplier_type:string; supplier_score:number; quote_code:string; currency:string; subtotal:number; freight:number; insurance:number; taxes:number; discount:number; total:number; lead_time_days:number; payment_terms:string|null; quality_notes:string|null; status:string; price_rank:number; };
type PO = { id:string; po_code:string; supplier_name:string|null; country:string|null; supplier_type:string|null; request_code:string|null; rfq_code:string|null; quote_code:string|null; po_type:string; currency:string; subtotal:number; freight:number; insurance:number; taxes:number; other_costs:number; total:number; status:string; order_date:string; expected_date:string|null; notes:string|null; items_count:number; };
type Supplier = { id:string; supplier_code:string; name:string; country:string; supplier_type:string; payment_terms:string; lead_time_days:number; currency:string; status:string; quality_score:number; delivery_score:number; price_score:number; weighted_score:number; po_count:number; total_purchased:number; notes:string|null; };
type ImportShipment = { id:string; shipment_code:string; po_code:string|null; supplier_name:string|null; origin_country:string; port_origin:string|null; port_destination:string|null; incoterm:string; container_type:string|null; etd:string|null; eta:string|null; status:string; merchandise_value:number; freight_cost:number; insurance_cost:number; customs_cost:number; local_transport:number; other_costs:number; landed_total:number; extra_costs_dop:number; cost_lines:number; notes:string|null; };

const money = (n:number|null|undefined, currency="DOP") => new Intl.NumberFormat("es-DO", { style:"currency", currency: currency === "USD" ? "USD" : "DOP", minimumFractionDigits:2 }).format(Number(n || 0));
function badge(v?:string|null){ if(["aprobada","adjudicada","seleccionada","emitida","recibida","cerrada","activo"].includes(v||"")) return "border-emerald-400/30 bg-emerald-500/15 text-emerald-300"; if(["borrador","enviada","abierta","cotizada","planificado","en_transito"].includes(v||"")) return "border-blue-400/30 bg-blue-500/15 text-blue-300"; if(["media","alta","aduana","parcial"].includes(v||"")) return "border-amber-400/30 bg-amber-500/15 text-amber-300"; return "border-slate-500/30 bg-slate-500/15 text-slate-300"; }

export default function ProcurementSourcingPage(){
 const [tab,setTab]=useState<Tab>("dashboard");
 const [dashboard,setDashboard]=useState<Dashboard>({total_requests:0,pending_requests:0,approved_requests:0,active_rfqs:0,supplier_quotes:0,open_pos:0,po_total:0,active_suppliers:0,active_imports:0});
 const [requests,setRequests]=useState<RequestRow[]>([]); const [rfqs,setRfqs]=useState<RFQ[]>([]); const [quotes,setQuotes]=useState<Quote[]>([]); const [pos,setPos]=useState<PO[]>([]); const [suppliers,setSuppliers]=useState<Supplier[]>([]); const [imports,setImports]=useState<ImportShipment[]>([]);
 const [search,setSearch]=useState(""); const [message,setMessage]=useState(""); const [loading,setLoading]=useState(false);
 async function loadData(){ try{ setLoading(true); setMessage(""); const [dashRes,reqRes,rfqRes,quoteRes,poRes,supRes,impRes]=await Promise.all([
  supabase.from("v_procurement_dashboard").select("*").maybeSingle(),
  supabase.from("v_procurement_requests_detail").select("*").order("created_at",{ascending:false}),
  supabase.from("v_procurement_rfq_detail").select("*").order("created_at",{ascending:false}),
  supabase.from("v_procurement_supplier_quotes_detail").select("*").order("total"),
  supabase.from("v_procurement_purchase_orders_detail").select("*").order("created_at",{ascending:false}),
  supabase.from("v_procurement_supplier_scorecards").select("*").order("weighted_score",{ascending:false}),
  supabase.from("v_procurement_import_shipments_detail").select("*").order("created_at",{ascending:false}),
 ]); [dashRes,reqRes,rfqRes,quoteRes,poRes,supRes,impRes].forEach((r:any)=>{ if(r.error) throw r.error; }); if(dashRes.data) setDashboard(dashRes.data as Dashboard); setRequests((reqRes.data||[]) as RequestRow[]); setRfqs((rfqRes.data||[]) as RFQ[]); setQuotes((quoteRes.data||[]) as Quote[]); setPos((poRes.data||[]) as PO[]); setSuppliers((supRes.data||[]) as Supplier[]); setImports((impRes.data||[]) as ImportShipment[]); }catch(e:any){ setMessage(e.message||"Error cargando Procurement."); } finally{ setLoading(false); } }
 useEffect(()=>{loadData();},[]);
 const filteredRequests=useMemo(()=>{const q=search.toLowerCase().trim(); if(!q)return requests; return requests.filter(r=>[r.request_code,r.title,r.department,r.priority,r.request_type,r.status,r.requested_by_name].filter(Boolean).join(" ").toLowerCase().includes(q));},[requests,search]);
 async function approveRequest(item:RequestRow){ try{setLoading(true); const {error}=await supabase.rpc("procurement_approve_request",{p_request_id:item.id,p_approver_name:"Ruben Santana"}); if(error)throw error; setMessage("Solicitud aprobada."); await loadData();}catch(e:any){setMessage(e.message||"No se pudo aprobar.");}finally{setLoading(false);} }
 async function createRfq(item:RequestRow){ try{setLoading(true); const {error}=await supabase.rpc("procurement_create_rfq_from_request",{p_request_id:item.id}); if(error)throw error; setMessage("RFQ creada."); await loadData();}catch(e:any){setMessage(e.message||"No se pudo crear RFQ.");}finally{setLoading(false);} }
 async function createPo(q:Quote){ try{setLoading(true); const {error}=await supabase.rpc("procurement_create_po_from_quote",{p_quote_id:q.id}); if(error)throw error; setMessage("Orden de compra generada."); await loadData();}catch(e:any){setMessage(e.message||"No se pudo crear PO.");}finally{setLoading(false);} }
 async function recalcImport(i:ImportShipment){ try{setLoading(true); const {error}=await supabase.rpc("procurement_calculate_landed_cost",{p_shipment_id:i.id}); if(error)throw error; setMessage("Landed cost recalculado."); await loadData();}catch(e:any){setMessage(e.message||"No se pudo recalcular.");}finally{setLoading(false);} }
 const nav=[ ["dashboard","Dashboard",BarChart3], ["solicitudes","Solicitudes",ClipboardList], ["rfq","RFQ",FileText], ["cotizaciones","Cotizaciones",DollarSign], ["ordenes","Órdenes",ShoppingCart], ["importaciones","Importaciones",Ship], ["proveedores","Proveedores",Store] ] as const;
 return <main className="min-h-screen bg-slate-950 text-white"><div className="mx-auto max-w-7xl px-4 py-6">
  <section className="mb-6 rounded-3xl border border-white/10 bg-gradient-to-br from-slate-900 via-slate-900 to-blue-950 p-6 shadow-2xl"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-sm uppercase tracking-[0.3em] text-blue-300">RD Wood System</p><h1 className="mt-2 text-3xl font-black tracking-tight lg:text-5xl">Procurement & Sourcing Pro</h1><p className="mt-2 max-w-3xl text-sm text-slate-300">Fase 28: solicitudes, RFQ, proveedores, órdenes de compra, importaciones y landed cost.</p></div><button onClick={loadData} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-blue-600 px-5 py-3 text-sm font-bold text-white shadow-lg hover:bg-blue-500"><RefreshCw size={18}/>Actualizar</button></div></section>
  {message&&<div className="mb-4 rounded-2xl border border-blue-400/30 bg-blue-500/10 px-4 py-3 text-sm text-blue-100">{message}</div>}{loading&&<div className="mb-4 rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-slate-300">Procesando...</div>}
  <section className="mb-6 grid grid-cols-2 gap-3 lg:grid-cols-9"><Kpi title="Solicitudes" value={dashboard.total_requests} icon={<ClipboardList size={20}/>}/><Kpi title="Pendientes" value={dashboard.pending_requests} icon={<FileText size={20}/>}/><Kpi title="Aprobadas" value={dashboard.approved_requests} icon={<CheckCircle2 size={20}/>}/><Kpi title="RFQ activas" value={dashboard.active_rfqs} icon={<FileText size={20}/>}/><Kpi title="Cotizaciones" value={dashboard.supplier_quotes} icon={<DollarSign size={20}/>}/><Kpi title="PO abiertas" value={dashboard.open_pos} icon={<ShoppingCart size={20}/>}/><Kpi title="Total PO" value={money(dashboard.po_total)} icon={<PackageCheck size={20}/>}/><Kpi title="Proveedores" value={dashboard.active_suppliers} icon={<Users size={20}/>}/><Kpi title="Imports" value={dashboard.active_imports} icon={<Ship size={20}/>}/></section>
  <section className="mb-6 flex gap-2 overflow-x-auto rounded-3xl border border-white/10 bg-white/5 p-2">{nav.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id as Tab)} className={`flex min-w-max items-center gap-2 rounded-2xl px-4 py-3 text-sm font-bold ${tab===id?"bg-white text-slate-950":"text-slate-300 hover:bg-white/10"}`}><Icon size={18}/>{label}</button>)}</section>
  {(tab==="dashboard"||tab==="solicitudes")&&<div className="mb-4 flex items-center gap-2 rounded-2xl border border-white/10 bg-slate-950 px-3 py-2"><Search size={18} className="text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar solicitud, proveedor, estado, departamento..." className="w-full bg-transparent text-sm outline-none placeholder:text-slate-500"/></div>}
  {tab==="dashboard"&&<section className="grid gap-4 lg:grid-cols-2"><Panel title="Solicitudes recientes" icon={<ClipboardList size={20}/>}>{filteredRequests.slice(0,6).map(r=><RequestCard key={r.id} item={r} onApprove={approveRequest} onRfq={createRfq}/>)}</Panel><Panel title="Importaciones activas" icon={<Ship size={20}/>}>{imports.slice(0,6).map(i=><ImportCard key={i.id} item={i} onRecalc={recalcImport}/>)}</Panel></section>}
  {tab==="solicitudes"&&<Panel title="Solicitudes de compra" icon={<ClipboardList size={20}/>}>{filteredRequests.map(r=><RequestCard key={r.id} item={r} onApprove={approveRequest} onRfq={createRfq}/>)}</Panel>}
  {tab==="rfq"&&<Panel title="RFQ / Solicitudes de cotización" icon={<FileText size={20}/>}>{rfqs.map(r=><div key={r.id} className="mb-3 rounded-2xl border border-white/10 bg-slate-900 p-4"><p className="font-black">{r.rfq_code} · {r.title}</p><p className="text-xs text-slate-400">Solicitud {r.request_code||"N/A"} · vence {r.due_date||"N/A"}</p><p className="mt-2 text-sm text-slate-300">{r.items_count} items · {r.quotes_count} cotizaciones · mejor {money(r.best_quote_total||0,r.currency)}</p><span className={`mt-2 inline-block rounded-full border px-3 py-1 text-xs font-black ${badge(r.status)}`}>{r.status}</span></div>)}</Panel>}
  {tab==="cotizaciones"&&<Panel title="Cotizaciones de proveedores" icon={<DollarSign size={20}/>}>{quotes.map(q=><QuoteCard key={q.id} item={q} onCreatePo={createPo}/>)}</Panel>}
  {tab==="ordenes"&&<Panel title="Órdenes de compra" icon={<ShoppingCart size={20}/>}>{pos.map(po=><div key={po.id} className="mb-3 rounded-2xl border border-white/10 bg-slate-900 p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><p className="font-black">{po.po_code} · {po.supplier_name}</p><p className="text-xs text-slate-400">{po.po_type} · {po.country} · esperado {po.expected_date||"N/A"}</p><p className="mt-2 text-sm text-slate-300">{po.items_count} items · {po.notes}</p></div><div className="text-right"><p className="text-2xl font-black text-emerald-300">{money(po.total,po.currency)}</p><span className={`mt-2 inline-block rounded-full border px-3 py-1 text-xs font-black ${badge(po.status)}`}>{po.status}</span></div></div></div>)}</Panel>}
  {tab==="importaciones"&&<Panel title="Importaciones y landed cost" icon={<Ship size={20}/>}>{imports.map(i=><ImportCard key={i.id} item={i} onRecalc={recalcImport}/>)}</Panel>}
  {tab==="proveedores"&&<Panel title="Scorecard de proveedores" icon={<Store size={20}/>}><div className="grid gap-3 lg:grid-cols-2">{suppliers.map(s=><div key={s.id} className="rounded-2xl border border-white/10 bg-slate-900 p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><p className="font-black">{s.supplier_code} · {s.name}</p><p className="text-xs text-slate-400">{s.country} · {s.supplier_type} · Lead {s.lead_time_days} días</p><p className="mt-2 text-sm text-slate-300">{s.notes}</p><p className="mt-1 text-xs text-slate-500">PO {s.po_count} · comprado {money(s.total_purchased,s.currency)}</p></div><div className="text-right"><p className="flex items-center justify-end gap-1 text-2xl font-black text-emerald-300"><Star size={18}/>{Number(s.weighted_score||0).toFixed(1)}</p><span className={`mt-2 inline-block rounded-full border px-3 py-1 text-xs font-black ${badge(s.status)}`}>{s.status}</span></div></div></div>)}</div></Panel>}
 </div></main>;
}
function RequestCard({item,onApprove,onRfq}:{item:RequestRow;onApprove:(r:RequestRow)=>void;onRfq:(r:RequestRow)=>void}){return <div className="mb-3 rounded-2xl border border-white/10 bg-slate-900 p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><p className="font-black">{item.request_code} · {item.title}</p><p className="text-xs text-slate-400">{item.department} · {item.request_type} · {item.requested_by_name||"N/A"}</p><p className="mt-2 text-sm text-slate-300">{item.description}</p><p className="mt-1 text-xs text-slate-500">{item.items_count} items · necesita {item.needed_by||"N/A"}</p><div className="mt-2 flex gap-2"><span className={`rounded-full border px-3 py-1 text-xs font-black ${badge(item.priority)}`}>{item.priority}</span><span className={`rounded-full border px-3 py-1 text-xs font-black ${badge(item.status)}`}>{item.status}</span></div></div><div className="flex flex-col gap-2 lg:items-end"><p className="text-2xl font-black text-emerald-300">{money(item.items_total||item.estimated_total)}</p><div className="flex gap-2">{!["aprobada","rfq","po_generada","cerrada"].includes(item.status)&&<button onClick={()=>onApprove(item)} className="rounded-xl bg-emerald-600 px-3 py-2 text-xs font-black text-white">Aprobar</button>}{item.status==="aprobada"&&<button onClick={()=>onRfq(item)} className="rounded-xl bg-blue-600 px-3 py-2 text-xs font-black text-white">Crear RFQ</button>}</div></div></div></div>}
function QuoteCard({item,onCreatePo}:{item:Quote;onCreatePo:(q:Quote)=>void}){return <div className="mb-3 rounded-2xl border border-white/10 bg-slate-900 p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><p className="font-black">#{item.price_rank} · {item.quote_code} · {item.supplier_name}</p><p className="text-xs text-slate-400">{item.rfq_code} · {item.country} · {item.supplier_type} · Lead {item.lead_time_days} días</p><p className="mt-2 text-sm text-slate-300">{item.quality_notes}</p><p className="mt-1 text-xs text-slate-500">Subtotal {money(item.subtotal,item.currency)} · freight {money(item.freight,item.currency)}</p></div><div className="flex flex-col gap-2 lg:items-end"><p className="text-2xl font-black text-emerald-300">{money(item.total,item.currency)}</p><span className={`rounded-full border px-3 py-1 text-xs font-black ${badge(item.status)}`}>{item.status}</span>{item.status!=="seleccionada"&&<button onClick={()=>onCreatePo(item)} className="rounded-xl bg-emerald-600 px-3 py-2 text-xs font-black text-white">Crear PO</button>}</div></div></div>}
function ImportCard({item,onRecalc}:{item:ImportShipment;onRecalc:(i:ImportShipment)=>void}){return <div className="mb-3 rounded-2xl border border-white/10 bg-slate-900 p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><p className="font-black">{item.shipment_code} · {item.supplier_name}</p><p className="text-xs text-slate-400">{item.origin_country} · {item.port_origin||"N/A"} → {item.port_destination||"RD"} · {item.incoterm}</p><p className="mt-2 text-sm text-slate-300">{item.notes}</p><p className="mt-1 text-xs text-slate-500">ETA {item.eta||"N/A"} · costos extra {money(item.extra_costs_dop)}</p></div><div className="flex flex-col gap-2 lg:items-end"><p className="text-2xl font-black text-emerald-300">{money(item.landed_total)}</p><span className={`rounded-full border px-3 py-1 text-xs font-black ${badge(item.status)}`}>{item.status}</span><button onClick={()=>onRecalc(item)} className="rounded-xl bg-blue-600 px-3 py-2 text-xs font-black text-white">Recalcular</button></div></div></div>}
function Kpi({title,value,icon}:{title:string;value:any;icon:React.ReactNode}){return <div className="rounded-3xl border border-white/10 bg-white/5 p-4 shadow-xl"><div className="mb-3 flex h-10 w-10 items-center justify-center rounded-2xl bg-blue-500/20 text-blue-200">{icon}</div><p className="text-xs uppercase tracking-widest text-slate-400">{title}</p><p className="mt-1 text-xl font-black">{value}</p></div>}
function Panel({title,icon,children}:{title:string;icon:React.ReactNode;children:React.ReactNode}){return <section className="rounded-3xl border border-white/10 bg-white/5 p-5 shadow-2xl"><div className="mb-4 flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-blue-500/20 text-blue-200">{icon}</div><h2 className="text-lg font-black">{title}</h2></div>{children}</section>}
